root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ."
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "yaml", "yml", "json", "env"] # Bổ sung các file cấu hình nếu cần
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = true                    # Bật poll mode cho WSL
  poll_interval = 1000           # Poll mỗi 1000 ms (1 giây)
  pre_cmd = ["rm -f ./tmp/main"] # Xoá binary cũ trước khi build
  post_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = true           # Không chạy binary cũ khi build fail

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = true   # Làm sạch màn hình khi rebuild
  keep_scroll = true

