version: '3.8'
services:
  backend:
    build: .
    container_name: go-fiber-api
    ports:
      - "4000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: example
      JWT_SECRET: secret
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: example
    ports:
      - "5432:5432"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
